### ISSUE TITLE
App crashes after this plugin is added

### ISSUE THREAD

**Issue by ryaa** [hinddeep/ionicCapacitorDarkMode#1]
I installed this plugin and made the required changed however the app is now crashing all the time with the below error

```
2020-07-04 22:01:51.211 3386-3386/io.kodesi.spiciko E/.kodesi.spicik: Invalid ID 0x00000000.
2020-07-04 22:01:51.410 3386-3386/io.kodesi.spiciko E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.kodesi.spiciko, PID: 3386
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.kodesi.spiciko/io.kodesi.spiciko.MainActivity}: android.view.InflateException: Binary XML file line #2 in io.kodesi.spiciko:layout/bridge_layout_main: Binary XML file line #2 in io.kodesi.spiciko:layout/bridge_layout_main: Error inflating class android.support.design.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```

Here is my MainActivity class
```
package io.kodesi.spiciko;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;

import com.bkon.capacitor.DarkMode.DarkMode;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);

      add(DarkMode.class);

    }});
  }
}
```

Is this plugin compatible with the latest capacitor version and androidX?

**Comment by ryaa** [comment]
https://www.npmjs.com/package/jetifier seems to help fixing the problem

**Comment by hinddeep** [comment]
Thanks for notifying. I'll update the plugin.

**Comment by hinddeep** [comment]
I've updated the plugin. It is now compatible with Android X and Capacitor 2.x out-of-the-box.
